AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 57

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/LineLength:
  Max: 133

Metrics/MethodLength:
  Max: 55

Metrics/PerceivedComplexity:
  Max: 13

Style/FormatString:
  Exclude:
    - 'lib/blackbox/number.rb'

Performance/RedundantMerge:
  Exclude:
      - 'lib/blackbox/gem.rb'
