AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 133

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 11

Style/FormatString:
  Exclude:
    - 'lib/blackbox/number.rb'

Performance/RedundantMerge:
  Exclude:
      - 'lib/blackbox/gem.rb'
