AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 42

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 42

Style/FormatString:
  Exclude:
    - 'lib/blackbox/number.rb'

Performance/RedundantMerge:
  Exclude:
      - 'lib/blackbox/gem.rb'
